defaultRetryCount: 2
defaultPollingDelay: 500
loggingConfig:
  logRequests: true,
  logResponses: true,
  logHeaders: true,
  logCookies: false,
  logTiming: true,
  logPayload: true,
  logUri: true,
  logQueryParams: false
